name: Standards Check
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  validate_standards:
    name: Validate Knowledge Base Standards
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install PyYAML jsonschema

        '
    - name: Run Standards Linter
      run: 'python tools/linter/kb_linter.py --repo-base . --directory master-knowledge-base
        --output linter_report.md --fail-on-errors

        '
    - name: Run Standards Indexer
      run: 'python tools/indexer/generate_index.py --repo-base . --src-dirs standards/src
        standards/registry standards/templates master-knowledge-base/tools master-knowledge-base
        --output-dir master-knowledge-base/dist --log-level INFO

        cp dist/standards_index.json standards_index.json # Copy for artifact upload

        '
    - name: Validate Index JSON against Schema
      run: 'jsonschema -i dist/standards_index.json tools/indexer/standards_index.schema.json

        '
    - name: Run Collection Builder
      run: 'python tools/builder/generate_collections.py --repo-base . --output-dir
        dist/collections --log-level INFO

        '
    - name: Upload Linter Report
      uses: actions/upload-artifact@v4
      with:
        name: linter-report
        path: linter_report.md
    - name: Upload Standards Index
      uses: actions/upload-artifact@v4
      with:
        name: standards-index
        path: standards_index.json
    - name: Upload Collection Output
      uses: actions/upload-artifact@v4
      with:
        name: collection-output
        path: dist/collections/
