global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: "scribe-engine"
    static_configs:
      - targets: ["scribe-engine:9469"]  # Scribe metrics endpoint
    metrics_path: /metrics
    scrape_interval: 10s
    
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]  # OpenTelemetry Collector Prometheus exporter
    metrics_path: /metrics
    scrape_interval: 15s