apiVersion: v1
kind: Secret
metadata:
  name: scribe-tls
  namespace: default
  labels:
    app: scribe
    component: tls
    hma.version: "2.2"
type: Opaque
data:
  # Base64 encoded TLS certificates and keys for mTLS
  # To generate these values, run the following commands from the repo root:
  #
  # ca.crt: cat ca.crt | base64 -w 0
  # server.crt: cat server.crt | base64 -w 0  
  # server.key: cat server.key | base64 -w 0
  #
  # Replace the placeholder values below with the actual base64 encoded certificate data
  
  ca.crt: {{ base64 of ca.crt }}
  server.crt: {{ base64 of server.crt }}
  server.key: {{ base64 of server.key }}

---
apiVersion: v1
kind: Secret
metadata:
  name: scribe-client-tls
  namespace: default
  labels:
    app: scribe
    component: client-tls
    hma.version: "2.2"
type: Opaque
data:
  # Client certificates for mTLS authentication
  # To generate these values, run:
  #
  # client.crt: cat client.crt | base64 -w 0
  # client.key: cat client.key | base64 -w 0
  
  client.crt: {{ base64 of client.crt }}
  client.key: {{ base64 of client.key }}