# .github/workflows/standards_check.yml

name: Standards Check

on:
  push:
    branches: [ main ] # Or your primary branch
  pull_request:
    branches: [ main ] # Or your primary branch

jobs:
  validate_standards:
    name: Validate Knowledge Base Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Using latest major version

      - name: Set up Python
        uses: actions/setup-python@v5 # Using latest major version
        with:
          python-version: '3.10' # Specify desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML jsonschema

      - name: Run Standards Linter
        run: |
          python master-knowledge-base/tools/linter/kb_linter.py --repo-base . --directory master-knowledge-base --output linter_report.md --fail-on-errors

      - name: Run Standards Indexer
        run: |
          python master-knowledge-base/tools/indexer/generate_index.py --repo-base . --src-dirs master-knowledge-base/standards/src master-knowledge-base/standards/registry master-knowledge-base/standards/templates master-knowledge-base/tools master-knowledge-base --output-dir master-knowledge-base/dist --log-level INFO
          cp master-knowledge-base/dist/standards_index.json standards_index.json # Copy for artifact upload

      - name: Validate Index JSON against Schema
        run: |
          jsonschema -i master-knowledge-base/dist/standards_index.json master-knowledge-base/tools/indexer/standards_index.schema.json

      - name: Run Collection Builder
        run: |
          python master-knowledge-base/tools/builder/generate_collections.py --repo-base . --output-dir master-knowledge-base/dist/collections --log-level INFO

      - name: Upload Linter Report
        uses: actions/upload-artifact@v4
        with:
          name: linter-report
          path: linter_report.md

      - name: Upload Standards Index
        uses: actions/upload-artifact@v4
        with:
          name: standards-index
          path: standards_index.json # Use the copied file from the root

      - name: Upload Collection Output
        uses: actions/upload-artifact@v4
        with:
          name: collection-output
          path: master-knowledge-base/dist/collections/

      # Conceptual "Post Linter Summary" step removed as per instructions.
      # Job failure (due to --fail-on-errors in linter or other script failures)
      # will be the primary indicator of issues.
      # The uploaded artifacts can be used for detailed review.
